// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Register And Login"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "User info",
                        "name": "Info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIError"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Registration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Register And Login"
                ],
                "summary": "Registarion",
                "parameters": [
                    {
                        "description": "User info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserRegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserRegisterResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIError"
                        }
                    }
                }
            }
        },
        "/tenders": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Tenderlar ro'yxatini olish uchun API endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Tenderlar ro'yxatini olish",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bir sahifadagi tenderlar soni (standart: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Sahifa raqami (standart: 1)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tenderlar muvaffaqiyatli qaytarildi",
                        "schema": {
                            "$ref": "#/definitions/model.GetAllTendersResp"
                        }
                    },
                    "400": {
                        "description": "Noto'g'ri parametrlar",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi yoki GetAllTenders funksiyasi ishlamadi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Yangi tender yaratish uchun API endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Tender yaratish",
                "parameters": [
                    {
                        "description": "Tender yaratish uchun talab qilinadigan ma'lumotlar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateTenderReqSwag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tender muvaffaqiyatli yaratildi",
                        "schema": {
                            "$ref": "#/definitions/model.CreateTenderResp"
                        }
                    },
                    "400": {
                        "description": "Ma'lumotlarni olishda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi yoki CreateTender funksiyasi ishlamadi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/tenders/all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve a list of tenders filtered by status or other parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contractor"
                ],
                "summary": "Get tenders by filters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (e.g., open, closed, awarded)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of tenders",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Tender"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/tenders/status_change/{id}/bids": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Tender uchun tanlangan taklifni statusini o'zgartirish",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Tanlangan taklifni belgilash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tender ID'si",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Taklif haqida ma'lumot",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SubmitBitReqSwag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Taklif muvaffaqiyatli belgilandi",
                        "schema": {
                            "$ref": "#/definitions/model.SubmitBitResp"
                        }
                    },
                    "400": {
                        "description": "Ma'lumotlarni olishda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi yoki BidAwarded funksiyasi ishlamadi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/tenders/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Mavjud tenderning ma'lumotlarini yangilash uchun API endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Tender ma'lumotlarini yangilash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tender ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tenderni yangilash uchun talab qilinadigan ma'lumotlar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateTenderReqSwag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tender ma'lumotlari muvaffaqiyatli yangilandi",
                        "schema": {
                            "$ref": "#/definitions/model.UpdateTenderResp"
                        }
                    },
                    "400": {
                        "description": "Ma'lumotlarni olishda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi yoki UpdateTender funksiyasi ishlamadi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Mavjud tenderni o'chirish uchun API endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Tenderni o'chirish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenderning ID'si",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tender muvaffaqiyatli o'chirildi",
                        "schema": {
                            "$ref": "#/definitions/model.DeleteTenderResp"
                        }
                    },
                    "500": {
                        "description": "Server xatosi yoki DeleteTender funksiyasi ishlamadi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/tenders/{id}/award/{bid_id}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Tender uchun tanlangan taklifni \"awarded\" sifatida belgilash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Tanlangan taklifni belgilash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tender ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Taklif ID",
                        "name": "bid_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Taklif muvaffaqiyatli belgilandi",
                        "schema": {
                            "$ref": "#/definitions/model.AwardTenderResp"
                        }
                    },
                    "400": {
                        "description": "Yaroqsiz ma'lumot yoki noto'g'ri so'rov",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "Tender yoki taklif topilmadi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi yoki AwardTender funksiyasi ishlamadi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/tenders/{id}/bids": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Contractor can get all bids of a tender with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contractor"
                ],
                "summary": "Get bids of tender",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tender ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Maximum price filter",
                        "name": "max_price",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Maximum delivery time filter (ISO8601 format)",
                        "name": "max_delivery_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of bids",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Bid"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Contractor can create bid to teender",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contractor"
                ],
                "summary": "Create bid",
                "parameters": [
                    {
                        "description": "bid infos (DeliveryTime format: dd-mm-yyyy)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateBid"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Tender id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi yoki CreateBid funksiyasi ishlamadi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/tenders/{id}/my/bids": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Client o'z tenderi uchun bildirilgan barcha takliflarni olish uchun API endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Tenderga bildirilgan takliflarni olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tender ID'si",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Bir sahifadagi takliflar soni (standart: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Sahifa raqami (standart: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Takliflarning boshlang'ich narxi (filtrlash uchun ixtiyoriy, float qiymat ko'rinishida yozilishi kerak, masalan: 100.50)",
                        "name": "start_price",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Takliflarning yakuniy narxi (filtrlash uchun ixtiyoriy, float qiymat ko'rinishida yozilishi kerak, masalan: 500.75)",
                        "name": "end_price",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Boshlanish sanasi (filtrlash uchun ixtiyoriy, format: YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tugash sanasi (filtrlash uchun ixtiyoriy, format: YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Takliflar muvaffaqiyatli qaytarildi",
                        "schema": {
                            "$ref": "#/definitions/model.GetTenderBidsResp"
                        }
                    },
                    "400": {
                        "description": "Ma'lumotlarni olishda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi yoki GetTenderBids funksiyasi ishlamadi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/users/{id}/bids": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve all bids placed by a contractor for various tenders, including tender details like title and deadline",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contractor"
                ],
                "summary": "Get Bid History for a Contractor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of bid history",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.BidHistory"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve bid history",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.AwardTenderResp": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                }
            }
        },
        "model.Bid": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "string"
                },
                "contractor_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "delivery_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "tender_id": {
                    "type": "string"
                }
            }
        },
        "model.BidHistory": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "string"
                },
                "contractor_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "delivery_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "tender_deadline": {
                    "type": "string"
                },
                "tender_id": {
                    "type": "string"
                },
                "tender_title": {
                    "type": "string"
                }
            }
        },
        "model.CreateBid": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "string"
                },
                "delivery_time": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "model.CreateTenderReqSwag": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "diadline": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.CreateTenderResp": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.DeleteTenderResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.GetAllTendersResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "tenders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tender"
                    }
                }
            }
        },
        "model.GetTenderBidsResp": {
            "type": "object",
            "properties": {
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Bid"
                    }
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "model.LoginResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "model.LoginUser": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.SubmitBitReqSwag": {
            "type": "object",
            "properties": {
                "bid_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.SubmitBitResp": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                }
            }
        },
        "model.Tender": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "number"
                },
                "client_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "diadline": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.UpdateTenderReqSwag": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "diadline": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.UpdateTenderResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.UserRegisterReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserRegisterResp": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "TENDER MANAGMENT API",
	Description:      "This is a sample API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
