services:
  redis-db:
    image: redis:latest
    container_name: redis
    ports: 
      - "6378:6379"
    networks:
      - tender 
    volumes:
      - redis_data:/data
  
  database:
    image: postgres:latest
    container_name: database 
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s
    ports:
      - "5454:5432"
    networks:
      - tender 
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?sslmode=disable",
      "up"
    ]
    depends_on:
      database:
        condition: service_healthy
    networks:
      - tender 
    volumes:
      - ./db/migrations:/migrations
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: redis
    depends_on:
      - database
      - redis-db
      - migrate
    networks:
      - tender  

volumes:
  db_data:
  redis_data:

networks:
  tender:
    driver: bridge